### ISSUE TITLE
Brightness?

### ISSUE THREAD

**Issue by Sungray** [digitalninja-ro/klipper-neopixel#9]
Hello,

Any way to change the maximum brightness in the template or as a parameter?

Thanks.

**Comment by digitalninja-ro** [comment]
Hello. Could you be a more specific? What MODE do you need to modify brightness? In GLOW mode this will reduce the contrast between low and high values. Not a good idea because will glow very little. Now, in PROGRESS mode, not all leds glows the same. The first one will have a brightness = 1/total_led and and with each one the brightness will increase until the last one that is the only one that glow at full intensity.

**Comment by digitalninja-ro** [comment]
After 6 days from the last answer, I assume @Sungray  did find the solution or give up.

**Comment by vjeko2404** [comment]
I would like to reopen this issue because I'm also not very happy with some of the brightness setting.
Is it possible to implement the brightness parameter into some of the types?
I would really want to be able to set the brightness (and even the color) in the print_percent / progress.

Thank you for your time and this great macro!
